### ISSUE TITLE
Travis fails to install sbt

### ISSUE THREAD

**Issue by exoego** [sbt/sbt-projectmatrix#6]
Travis fails installing sbt from bintray due to missing key.
https://travis-ci.org/sbt/sbt-projectmatrix/builds/529648888?utm_source=github_status&utm_medium=notification

https://github.com/sbt/sbt-projectmatrix/blob/a2bf5b9b7634c56b51c0f8886267dc4e714bf0d9/.travis.yml#L14-L16

`sourceline` and `key_url` should exist in same object.

```yaml
  sources:
     - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
       key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=sbt'
```
